services:
  telemedicine-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://lasannavodya:DelLCS5EiIBT3jFu@course.uf2pi.mongodb.net/HealthCare?retryWrites=true&w=majority&appName=Course
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8081/api/appointment
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - USER_EVENTS_EXCHANGE=healthcare.user.events
      - USER_EVENTS_QUEUE=telemedicine.user.events
      - USER_EVENTS_ENABLED=true
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
