apiVersion: v1
kind: Secret
metadata:
  name: telemedicine-secret
  namespace: healthcare
type: Opaque
stringData:
  JWT_SECRET: dev-secret-change-me
  JWT_EXPIRATION_MS: "86400000"
  RABBITMQ_PASSWORD: guest
  VPAAS_MAGIC_COOKIE: ""
